all: Data/poblaciones_30_20.pdf Data/poblaciones_29_20.pdf Data/poblaciones_28_20.pdf Data/poblaciones_27_20.pdf Data/poblaciones_26_20.pdf Data/poblaciones_25_20.pdf Data/poblaciones_24_20.pdf Data/poblaciones_23_20.pdf Data/poblaciones_22_20.pdf Data/poblaciones_21_20.pdf Data/poblaciones_20_20.pdf Data/poblaciones_19_20.pdf Data/poblaciones_18_20.pdf Data/poblaciones_17_20.pdf Data/poblaciones_16_20.pdf Data/poblaciones_15_20.pdf Data/poblaciones_14_20.pdf Data/poblaciones_13_20.pdf Data/poblaciones_12_20.pdf Data/poblaciones_11_20.pdf Data/poblaciones_10_20.pdf Data/poblaciones_9_20.pdf Data/poblaciones_8_20.pdf Data/poblaciones_7_20.pdf Data/poblaciones_6_20.pdf Data/poblaciones_5_20.pdf Data/poblaciones_4_20.pdf Data/poblaciones_3_20.pdf Data/poblaciones_2_20.pdf Data/poblaciones_1_20.pdf 

Data/poblaciones_30_20.pdf: Data/poblaciones_30_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_30_20.dat

Data/poblaciones_30_20.dat: a.out
	./a.out 30 20

Data/poblaciones_29_20.pdf: Data/poblaciones_29_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_29_20.dat

Data/poblaciones_29_20.dat: a.out
	./a.out 29 20

Data/poblaciones_28_20.pdf: Data/poblaciones_28_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_28_20.dat

Data/poblaciones_28_20.dat: a.out
	./a.out 28 20

Data/poblaciones_27_20.pdf: Data/poblaciones_27_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_27_20.dat

Data/poblaciones_27_20.dat: a.out
	./a.out 27 20

Data/poblaciones_26_20.pdf: Data/poblaciones_26_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_26_20.dat

Data/poblaciones_26_20.dat: a.out
	./a.out 26 20

Data/poblaciones_25_20.pdf: Data/poblaciones_25_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_25_20.dat

Data/poblaciones_25_20.dat: a.out
	./a.out 25 20

Data/poblaciones_24_20.pdf: Data/poblaciones_24_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_24_20.dat

Data/poblaciones_24_20.dat: a.out
	./a.out 24 20

Data/poblaciones_23_20.pdf: Data/poblaciones_23_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_23_20.dat

Data/poblaciones_23_20.dat: a.out
	./a.out 23 20

Data/poblaciones_22_20.pdf: Data/poblaciones_22_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_22_20.dat

Data/poblaciones_22_20.dat: a.out
	./a.out 22 20

Data/poblaciones_21_20.pdf: Data/poblaciones_21_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_21_20.dat

Data/poblaciones_21_20.dat: a.out
	./a.out 21 20

Data/poblaciones_20_20.pdf: Data/poblaciones_20_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_20_20.dat

Data/poblaciones_20_20.dat: a.out
	./a.out 20 20

Data/poblaciones_19_20.pdf: Data/poblaciones_19_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_19_20.dat

Data/poblaciones_19_20.dat: a.out
	./a.out 19 20

Data/poblaciones_18_20.pdf: Data/poblaciones_18_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_18_20.dat

Data/poblaciones_18_20.dat: a.out
	./a.out 18 20

Data/poblaciones_17_20.pdf: Data/poblaciones_17_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_17_20.dat

Data/poblaciones_17_20.dat: a.out
	./a.out 17 20

Data/poblaciones_16_20.pdf: Data/poblaciones_16_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_16_20.dat

Data/poblaciones_16_20.dat: a.out
	./a.out 16 20

Data/poblaciones_15_20.pdf: Data/poblaciones_15_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_15_20.dat

Data/poblaciones_15_20.dat: a.out
	./a.out 15 20

Data/poblaciones_14_20.pdf: Data/poblaciones_14_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_14_20.dat

Data/poblaciones_14_20.dat: a.out
	./a.out 14 20

Data/poblaciones_13_20.pdf: Data/poblaciones_13_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_13_20.dat

Data/poblaciones_13_20.dat: a.out
	./a.out 13 20

Data/poblaciones_12_20.pdf: Data/poblaciones_12_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_12_20.dat

Data/poblaciones_12_20.dat: a.out
	./a.out 12 20

Data/poblaciones_11_20.pdf: Data/poblaciones_11_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_11_20.dat

Data/poblaciones_11_20.dat: a.out
	./a.out 11 20

Data/poblaciones_10_20.pdf: Data/poblaciones_10_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_10_20.dat

Data/poblaciones_10_20.dat: a.out
	./a.out 10 20

Data/poblaciones_9_20.pdf: Data/poblaciones_9_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_9_20.dat

Data/poblaciones_9_20.dat: a.out
	./a.out 9 20

Data/poblaciones_8_20.pdf: Data/poblaciones_8_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_8_20.dat

Data/poblaciones_8_20.dat: a.out
	./a.out 8 20

Data/poblaciones_7_20.pdf: Data/poblaciones_7_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_7_20.dat

Data/poblaciones_7_20.dat: a.out
	./a.out 7 20

Data/poblaciones_6_20.pdf: Data/poblaciones_6_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_6_20.dat

Data/poblaciones_6_20.dat: a.out
	./a.out 6 20

Data/poblaciones_5_20.pdf: Data/poblaciones_5_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_5_20.dat

Data/poblaciones_5_20.dat: a.out
	./a.out 5 20

Data/poblaciones_4_20.pdf: Data/poblaciones_4_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_4_20.dat

Data/poblaciones_4_20.dat: a.out
	./a.out 4 20

Data/poblaciones_3_20.pdf: Data/poblaciones_3_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_3_20.dat

Data/poblaciones_3_20.dat: a.out
	./a.out 3 20

Data/poblaciones_2_20.pdf: Data/poblaciones_2_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_2_20.dat

Data/poblaciones_2_20.dat: a.out
	./a.out 2 20

Data/poblaciones_1_20.pdf: Data/poblaciones_1_20.dat plot_poblaciones.py
	python plot_poblaciones.py Data/poblaciones_1_20.dat

Data/poblaciones_1_20.dat: a.out
	./a.out 1 20

a.out: runge_kutta.c 
	cc runge_kutta.c 

clear:
	rm -f Data/*
	rm -f a.out
